/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BanditBaseInterface extends Interface {
    getFunction(nameOrSignature: "getMessage" | "identity" | "lastUpdated" | "message" | "owner" | "transferOwnership" | "updateMessage"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MessageUpdated" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'getMessage', values?: undefined): string;
encodeFunctionData(functionFragment: 'identity', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastUpdated', values?: undefined): string;
encodeFunctionData(functionFragment: 'message', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateMessage', values: [string]): string;

    decodeFunctionResult(functionFragment: 'getMessage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'identity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastUpdated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'message', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateMessage', data: BytesLike): Result;
  }

  
    export namespace MessageUpdatedEvent {
      export type InputTuple = [updater: AddressLike, newMessage: string, timestamp: BigNumberish];
      export type OutputTuple = [updater: string, newMessage: string, timestamp: bigint];
      export interface OutputObject {updater: string, newMessage: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BanditBase extends BaseContract {
    
    connect(runner?: ContractRunner | null): BanditBase;
    waitForDeployment(): Promise<this>;

    interface: BanditBaseInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getMessage: TypedContractMethod<
      [],
      [[string, bigint, string]],
      'view'
    >
    

    
    identity: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    lastUpdated: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    message: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateMessage: TypedContractMethod<
      [newMessage: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getMessage'): TypedContractMethod<
      [],
      [[string, bigint, string]],
      'view'
    >;
getFunction(nameOrSignature: 'identity'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lastUpdated'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'message'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateMessage'): TypedContractMethod<
      [newMessage: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'MessageUpdated'): TypedContractEvent<MessageUpdatedEvent.InputTuple, MessageUpdatedEvent.OutputTuple, MessageUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'MessageUpdated(address,string,uint256)': TypedContractEvent<MessageUpdatedEvent.InputTuple, MessageUpdatedEvent.OutputTuple, MessageUpdatedEvent.OutputObject>;
      MessageUpdated: TypedContractEvent<MessageUpdatedEvent.InputTuple, MessageUpdatedEvent.OutputTuple, MessageUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }